-- Matches (bracket games per tournament)
-- Run after `tournaments`, `tournament_teams`, and `users` exist.

CREATE TABLE IF NOT EXISTS public.matches (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tournament_id uuid NOT NULL REFERENCES public.tournaments(id) ON DELETE CASCADE,
  round integer NOT NULL,
  team1_id uuid NOT NULL REFERENCES public.tournament_teams(id) ON DELETE RESTRICT,
  team2_id uuid NOT NULL REFERENCES public.tournament_teams(id) ON DELETE RESTRICT,
  scheduled_time timestamptz,
  status text NOT NULL DEFAULT 'scheduled',
  winner_id uuid REFERENCES public.tournament_teams(id) ON DELETE SET NULL,
  riot_match_id text,
  lobby_parameters jsonb,
  referee_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT matches_status_check CHECK (
    status IN ('scheduled', 'in_progress', 'completed', 'disputed')
  ),
  CONSTRAINT matches_teams_different CHECK (team1_id <> team2_id)
);

CREATE INDEX IF NOT EXISTS idx_matches_tournament_id ON public.matches(tournament_id);
CREATE INDEX IF NOT EXISTS idx_matches_team1_id ON public.matches(team1_id);
CREATE INDEX IF NOT EXISTS idx_matches_team2_id ON public.matches(team2_id);
CREATE INDEX IF NOT EXISTS idx_matches_winner_id ON public.matches(winner_id);
CREATE INDEX IF NOT EXISTS idx_matches_referee_id ON public.matches(referee_id);
CREATE INDEX IF NOT EXISTS idx_matches_riot_match_id ON public.matches(riot_match_id) WHERE riot_match_id IS NOT NULL;

COMMENT ON TABLE public.matches IS 'Bracket matches; lobby_parameters generated by platform, validated via Riot API or manual';
